#!/usr/bin/python3
#+
# Test of trying to parse the contents of .blend files created by
# Blender <http://www.blender.org/>. Invoke this script as follows:
#
#     blendparse blendfile
#
# where blendfile is the name of a .blend file to analyze.
# The output of the script will be a dump of the decoded file contents.
#
# Copyright 2012 Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#-

import sys

import blendfile

#+
# Mainline
#-

if len(sys.argv) != 2 :
    raise RuntimeError("need one arg, the name of the .blend file to parse")
#end if
log = sys.stdout
blend = blendfile.Blenddata().load(sys.argv[1], keep_rawdata = True, log = log)
for i, block in enumerate(blend.blocks) :
    log.write("block %d(%s)[%s] : %s[%d]\n" % (i, repr(block["code"]), len(block["rawdata"]), block["type"]["name"], block["dna_count"])) # debug
    for item in block["data"] :
        log.write(" => " + repr(item) + "\n")
    #end for
#end for

